# Generated by Django 3.2.3 on 2021-10-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0002_auto_20211011_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name and surname')),
                ('position', models.CharField(max_length=150, verbose_name='Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Out team',
                'ordering': ['-id'],
            },
        ),
    ]
