# Generated by Django 3.2.3 on 2021-10-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Our team'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
    ]
