# Generated by Django 3.2.3 on 2021-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0007_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category of Action',
                'verbose_name_plural': 'Categories of Activites',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='act',
            name='act',
            field=models.ManyToManyField(blank=True, to='En.ActCategory', verbose_name='Category'),
        ),
    ]
