# Generated by Django 3.2.3 on 2021-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0010_practice_practice_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_form',
            name='practice',
            field=models.ManyToManyField(blank=True, to='En.Practice', verbose_name='Practice'),
        ),
    ]
