# Generated by Django 3.2.3 on 2021-10-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0011_practice_form_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice_form',
            name='practice',
        ),
    ]
