# Generated by Django 3.2.3 on 2021-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0013_practice_form_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joinus_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('surname', models.CharField(max_length=150, verbose_name='Surname')),
                ('jobs', models.CharField(max_length=150, verbose_name='Jobs')),
                ('phone', models.CharField(max_length=150, verbose_name='Phone')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Join us',
                'verbose_name_plural': 'Join us',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Active Member', 'verbose_name_plural': 'Active Members'},
        ),
    ]
