# Generated by Django 3.2.3 on 2021-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0016_vacancy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='target',
            field=models.CharField(blank=True, max_length=150, verbose_name='data-target'),
        ),
    ]
