# Generated by Django 3.2.3 on 2021-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('En', '0019_auto_20211014_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='actcategory',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='service',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='key',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='keywords'),
        ),
    ]
