# Generated by Django 3.2.3 on 2021-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil 3'),
        ),
    ]
