# Generated by Django 3.2.3 on 2021-10-11 20:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Fəaliyyət',
                'verbose_name_plural': 'Fəaliyyətlər',
                'ordering': ['-id'],
            },
        ),
    ]
