# Generated by Django 3.2.3 on 2021-10-12 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0008_auto_20211012_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Xidmətin kateqoriyası',
                'verbose_name_plural': 'Xidmətin kateqoriyaları',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('serv', models.ManyToManyField(blank=True, to='Az.ServiceCategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['-id'],
            },
        ),
    ]
