# Generated by Django 3.2.3 on 2021-10-13 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0009_service_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Təlim',
                'verbose_name_plural': 'Təlimlər',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Practice_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('jobs', models.CharField(max_length=150, verbose_name='İş yeri')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefon')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Practice form page',
                'verbose_name_plural': 'Practice form page',
                'ordering': ['-id'],
            },
        ),
    ]
