# Generated by Django 3.2.3 on 2021-10-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0012_remove_practice_form_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_form',
            name='practice',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Təlimin adı'),
        ),
    ]
