# Generated by Django 3.2.3 on 2021-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0013_practice_form_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joinus_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('jobs', models.CharField(max_length=150, verbose_name='İş yeri')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefon')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Bizə qoşul',
                'verbose_name_plural': 'Bizə qoşul',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Aktiv Üzv', 'verbose_name_plural': 'Aktiv Üzvlərimiz'},
        ),
    ]
