# Generated by Django 3.2.3 on 2021-10-14 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0014_auto_20211014_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('about', ckeditor.fields.RichTextField(verbose_name='İş haqqında')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Tələblər')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-id'],
            },
        ),
    ]
