# Generated by Django 3.2.3 on 2021-10-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0017_vacancy_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
    ]
