# Generated by Django 3.2.3 on 2021-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Az', '0018_blog_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='actcategory',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='practice',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='service',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='key',
            field=models.CharField(blank=True, max_length=150, verbose_name='keywords'),
        ),
    ]
