# Generated by Django 3.2.3 on 2021-10-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_index_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index_about',
        ),
    ]
