# Generated by Django 3.2.3 on 2021-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_index_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Slaydın başlığı')),
                ('content', models.CharField(max_length=150, verbose_name='Slaydın mətni')),
                ('link', models.CharField(max_length=150, verbose_name='Slaydın gedəcəyi ünvan')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
                'ordering': ['-id'],
            },
        ),
    ]
