# Generated by Django 3.2.3 on 2021-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AddField(
            model_name='slider',
            name='item',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item'),
        ),
    ]
