# Generated by Django 3.2.3 on 2021-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20211018_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='content_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Slaydın mətni - en'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Slaydın başlığı - en'),
        ),
    ]
