# Generated by Django 3.2.3 on 2021-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20211018_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('title', models.CharField(max_length=150, verbose_name='Logonun adı')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logolar',
            },
        ),
    ]
