# Generated by Django 3.2.3 on 2021-10-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link'),
        ),
    ]
