# Generated by Django 3.2.3 on 2021-10-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_logo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partniors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Logo')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Partnior',
                'verbose_name_plural': 'Partniorlar',
            },
        ),
    ]
