# Generated by Django 3.2.3 on 2021-10-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_partniors'),
    ]

    operations = [
        migrations.AddField(
            model_name='partniors',
            name='item',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item'),
        ),
    ]
